### ISSUE TITLE
Sporadic crash when running tests

### ISSUE THREAD

**Issue by robertknight** [emotechlab/silero-rs#20]
When running `cargo test --all-features` I occasionally experience a crash. So far I've seen a few different errors when this happens:

```
running 6 tests
test chunk_20_default_params_16k ... FAILED
error: test failed, to rerun pass `--test snapshot`

Caused by:
  process didn't exit successfully: `/Users/robert/other/silero-rs/target/debug/deps/snapshot-922dfd7ba42f0d16` (signal: 11, SIGSEGV: invalid memory reference)
```

```
---- chunk_30_default_params_16k stdout ----
thread 'chunk_30_default_params_16k' panicked at /Users/robert/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ort-2.0.0-rc.4/src/environment.rs:51:9:
assertion `left != right` failed
  left: 0x0
 right: 0x0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    chunk_30_default_params_16k
```

```
snapshot-922dfd7ba42f0d16(48386,0x700009d8f000) malloc: Heap corruption detected, free list is damaged at 0x600000f90600
*** Incorrect guard value: 60851421382143
snapshot-922dfd7ba42f0d16(48386,0x700009d8f000) malloc: *** set a breakpoint in malloc_error_break to debug
error: test failed, to rerun pass `--test snapshot`
```

I can reproduce the problem with a script which runs the tests in a loop:

```sh
#!/bin/sh

for i in {1..100}
do
    echo "Running test iteration $i"
    cargo test --all-features
done
```

I'm using rustc v1.80.0 on an Intel Mac running macOS 14.4.1. Tested with commit 00fccb247c18eb0274655e7acb593885d7362048.

There is no unsafe code in this crate so the problem must be something that the `ort` crate is doing that is somehow being triggered by this crate. Looking at `ort-2.0.0-rc.4/src/environment.rs:51`(from the log above) I suspect this might be an issue with concurrent initialization of the library by multiple threads in cargo's test runner.

**Comment by xd009642** [comment]
So I think you're right on the cause I've raised an issue in ort and I'll see what they say. Might figure out if there's a nice way we can initialise the env in a thread safe way in the `VadSession` :thinking:
